// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.AddAnyFile
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddAnyFilePkgString = "49335c7b-857d-42bd-ae53-3bfa8a4b5ad9";
        public static Guid guidAddAnyFilePkg = new Guid(guidAddAnyFilePkgString);

        public const string guidAddAnyFileCmdSetString = "3c875207-67c2-4ad7-88b3-91f2ca302c0f";
        public static Guid guidAddAnyFileCmdSet = new Guid(guidAddAnyFileCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidMyCommand = 0x0100;
    }
}