// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.AddAnyFile
{
    internal sealed partial class Vsix
    {
        public const string Id = "2D005365-A798-4B47-9E54-FFD05AAB8B7F";
        public const string Name = "Custom Add New File (64-bit)";
        public const string Description = @"The fastest and easiest way to add new files to any project - including files that start with a dot";
        public const string Language = "en-US";
        public const string Version = "4.6";
        public const string Author = "Mads Kristensen";
        public const string Tags = "file, add, template";
    }
}
